version: '3.8'

services:
  ouster_ros_driver_pkg:           # <-- YOUR TODO: change to name of your repository
    # depends_on: 
      # - master          
      # - <package>          # <-- YOUR TODO: change dependencies to other packages
    build:
      context: .  
      dockerfile: Dockerfile
    image: ouster_ros_driver_pkg:latest        # <-- YOUR TODO: change to name of your repository
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PACKAGE_NAME=ouster_ros_driver_pkg     # <-- YOUR TODO: change to name of your repository
      - OUSTER_HOSTNAME=${LIDAR_IP_ADDRESS}
      - XAVIER_IP=${XAVIER_IP}
      # - ROS_MASTER_URI=http://master:11311 
    volumes:
      - ./:/ws/src/ouster_ros_driver_pkg       # <-- YOUR TODO: change to name of your repository
    entrypoint: /ws/src/ouster_ros_driver_pkg/docker-entrypoint.sh  # <-- YOUR TODO: change to name of your repository
    command: bash -c "source devel/setup.bash" && roslaunch ouster_ros ouster.launch"    
