version: '3.8'

services:
  master:
    container_name: 
      master-container
    image: ros:noetic-ros-core-focal
    environment:
      - ROS_DISTRO=noetic
    restart: unless-stopped
    network_mode: host
    command: bash -c "source /opt/ros/noetic/setup.bash && roscore"

  ouster_ros_driver_pkg:           # <-- YOUR TODO: change to name of your repository
    # depends_on: 
      # - master          
      # - <package>          # <-- YOUR TODO: change dependencies to other packages
    build:
      context: .  
      dockerfile: Dockerfile
    image: ouster_ros_driver_pkg:latest        # <-- YOUR TODO: change to name of your repository
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PACKAGE_NAME=ouster_ros_driver_pkg     # <-- YOUR TODO: change to name of your repository
      - OUSTER_HOSTNAME=${LIDAR_IP_ADDRESS}
      - XAVIER_IP=${XAVIER_IP}
      # - ROS_MASTER_URI=http://master:11311 
    volumes:
      - ./:/ws/src/ouster_ros_driver_pkg       # <-- YOUR TODO: change to name of your repository
    entrypoint: /ws/src/ouster_ros_driver_pkg/docker-entrypoint.sh  # <-- YOUR TODO: change to name of your repository
    command: bash -c "source /ws/devel/setup.bash && roslaunch ouster_ros ouster.launch"    
